### ISSUE TITLE
Error running with Rails 7.0 alpha

### ISSUE THREAD

**Issue by noelrappin** [bibendi/activerecord-postgres_enum#50]
**Describe the bug**
activerecord-postgres_enum is not compatible with Rails 7.0 alpha

**To Reproduce**
Upgrade to Rails 7.0 alpha
Run db:migrate

Error:

`ArgumentError: wrong number of arguments (given 1, expected 0)`
```
/Users/noel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-061bf3156fb9/activemodel/lib/active_model/type/value.rb:8:in `initialize'
/Users/noel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-postgres_enum-0.6.0/lib/active_record/postgres_enum/extensions.rb:12:in `initialize'
/Users/noel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-postgres_enum-0.6.0/lib/active_record/postgres_enum/extensions.rb:19:in `new'
/Users/noel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-postgres_enum-0.6.0/lib/active_record/postgres_enum/extensions.rb:19:in `register_enum_type'
```

**Expected behavior**
No error

**Context (please complete the following information):**
 - OS: MacOS
 - Version most recent version of this gem, Rails 7.0 alpha

**Comment by bouk** [comment]
You're using version 0.6.0, it works on 1.6.1

**Comment by noelrappin** [comment]
Then 1.6.1 needs to change it's dependencies to allow for Rails 7

```
activerecord-postgres_enum (= 1.6.1) was resolved to 1.6.1, which depends on
      activerecord (>= 5, < 6.2)
```

Thanks!

**Comment by noelrappin** [comment]
https://github.com/noelrappin/activerecord-postgres_enum I can submit it as a PR if you'd like
